# Generated by Django 3.1.1 on 2020-12-10 11:49

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(upload_to=management.models.get_upload_path),
        ),
    ]
