# Generated by Django 3.1.1 on 2020-12-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
