# Generated by Django 3.1.1 on 2020-12-04 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_auto_20201204_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('profile_photo', models.ImageField(upload_to=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='usergallery',
            name='photographer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.profile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
