# Generated by Django 3.1.1 on 2020-12-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20201205_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='usergallery',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
