# Generated by Django 3.1.4 on 2020-12-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergallery',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
