# Generated by Django 3.1.1 on 2020-12-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_album', '0005_auto_20201209_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergallery',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
